//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolLibrary0._1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book_category
    {
        public int book_category_id { get; set; }
        public Nullable<int> book_id { get; set; }
        public Nullable<int> category_id { get; set; }
    
        public virtual book book { get; set; }
        public virtual category category { get; set; }
    }
}
